baseurl = "http://prgcont.cz/"
languageCode = "en-us"
title = "Prague Container Meetup"
theme = "hugo-creative-theme"
publishDir = "docs"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Prague Containers Meetup"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Prague Container Meetup"
		subtitle   = "Welcome to [Prague Containers Meetup](https://www.meetup.com/Prague-Containers-Meetup/) group."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Prague, containers and friends"
		description = "We are a community with a mission to connect people interested in containers, cloud and devops topics."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
                icon = "fa-meetup"
                title = "Get social!"
                description = "Join our [meetup group](https://www.meetup.com/Prague-Containers-Meetup)."

	[[params.services.list]]
                icon = "fa-podcast"
                title = "We want you to speak!"
                description = "[Submit](https://docs.google.com/a/l-d-j.org/forms/d/e/1FAIpQLSd5wAgmpjevYnLymlVEKPf6kOx_07Fun_wA-Fpd1dg4yekdUQ/viewform) your talk proposal"

        [[params.services.list]]
                icon = "fa-github-alt"
                title = "I want to help."
                description = "Check our github [repos](https://www.github.com/prgcont)"

        [[params.services.list]]
                icon = "fa-slack"
                title = "Where do you live."
                description = "[Join our slack!](https://prgcont.slack.com/)"


